/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBWIN32WINDOWHELPERFIELDS_H_
#define _OSGTBWIN32WINDOWHELPERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGWindowDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TBWIN32WindowHelper;

OSG_GEN_CONTAINERPTR(TBWIN32WindowHelper);
/*! \ingroup GrpWindowWIN32FieldTraits
    \ingroup GrpLibOSGWindow
 */
template <>
struct FieldTraits<TBWIN32WindowHelper *, nsOSG> :
    public FieldTraitsFCPtrBase<TBWIN32WindowHelper *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TBWIN32WindowHelper *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_WINDOW_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTBWIN32WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32WindowHelper *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTBWIN32WindowHelperPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32WindowHelper *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTBWIN32WindowHelperPtr;
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32WindowHelper *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTBWIN32WindowHelperPtr;
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32WindowHelper *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTBWIN32WindowHelperPtr;
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32WindowHelper *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTBWIN32WindowHelperPtr;


/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32WindowHelper *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTBWIN32WindowHelperPtr;
/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32WindowHelper *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTBWIN32WindowHelperPtr;
/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32WindowHelper *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTBWIN32WindowHelperPtr;
/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32WindowHelper *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTBWIN32WindowHelperPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindow */
struct SFRecTBWIN32WindowHelperPtr : 
    public PointerSField<TBWIN32WindowHelper *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindow */
struct SFUnrecTBWIN32WindowHelperPtr : 
    public PointerSField<TBWIN32WindowHelper *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindow */
struct SFWeakTBWIN32WindowHelperPtr :
    public PointerSField<TBWIN32WindowHelper *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindow */
struct SFUncountedTBWIN32WindowHelperPtr :
    public PointerSField<TBWIN32WindowHelper *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindow */
struct MFRecTBWIN32WindowHelperPtr :
    public PointerMField<TBWIN32WindowHelper *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindow */
struct MFUnrecTBWIN32WindowHelperPtr :
    public PointerMField<TBWIN32WindowHelper *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindow */
struct MFWeakTBWIN32WindowHelperPtr :
    public PointerMField<TBWIN32WindowHelper *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindow */
struct MFUncountedTBWIN32WindowHelperPtr :
    public PointerMField<TBWIN32WindowHelper *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTBWIN32WINDOWHELPERFIELDS_H_ */
