/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TBWIN32WindowHelper!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGTBWIN32WindowHelperBase.h"
#include "OSGTBWIN32WindowHelper.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TBWIN32WindowHelper
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TBWIN32WindowHelper *, nsOSG>::_type(
    "TBWIN32WindowHelperPtr", 
    "WIN32WindowPtr", 
    TBWIN32WindowHelper::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TBWIN32WindowHelper *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TBWIN32WindowHelper *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TBWIN32WindowHelper *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TBWIN32WindowHelperBase::classDescInserter(TypeObject &oType)
{
}


TBWIN32WindowHelperBase::TypeObject TBWIN32WindowHelperBase::_type(
    TBWIN32WindowHelperBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TBWIN32WindowHelperBase::createEmptyLocal),
    TBWIN32WindowHelper::initMethod,
    TBWIN32WindowHelper::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TBWIN32WindowHelper::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TBWIN32WindowHelper\"\n"
    "    parent=\"WIN32Window\"\n"
    "    library=\"Window\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    docGroupBase=\"GrpWindowWIN32\"\n"
    "    >\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TBWIN32WindowHelperBase::getType(void)
{
    return _type;
}

const FieldContainerType &TBWIN32WindowHelperBase::getType(void) const
{
    return _type;
}

UInt32 TBWIN32WindowHelperBase::getContainerSize(void) const
{
    return sizeof(TBWIN32WindowHelper);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT TBWIN32WindowHelperBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TBWIN32WindowHelperBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TBWIN32WindowHelperBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TBWIN32WindowHelperTransitPtr TBWIN32WindowHelperBase::createLocal(BitVector bFlags)
{
    TBWIN32WindowHelperTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TBWIN32WindowHelper>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TBWIN32WindowHelperTransitPtr TBWIN32WindowHelperBase::createDependent(BitVector bFlags)
{
    TBWIN32WindowHelperTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TBWIN32WindowHelper>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TBWIN32WindowHelperTransitPtr TBWIN32WindowHelperBase::create(void)
{
    TBWIN32WindowHelperTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TBWIN32WindowHelper>(tmpPtr);
    }

    return fc;
}

TBWIN32WindowHelper *TBWIN32WindowHelperBase::createEmptyLocal(BitVector bFlags)
{
    TBWIN32WindowHelper *returnValue;

    newPtr<TBWIN32WindowHelper>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TBWIN32WindowHelper *TBWIN32WindowHelperBase::createEmpty(void)
{
    TBWIN32WindowHelper *returnValue;

    newPtr<TBWIN32WindowHelper>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TBWIN32WindowHelperBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TBWIN32WindowHelper *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBWIN32WindowHelper *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBWIN32WindowHelperBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TBWIN32WindowHelper *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBWIN32WindowHelper *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBWIN32WindowHelperBase::shallowCopy(void) const
{
    TBWIN32WindowHelper *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TBWIN32WindowHelper *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

TBWIN32WindowHelperBase::TBWIN32WindowHelperBase(void) :
    Inherited()
{
}

TBWIN32WindowHelperBase::TBWIN32WindowHelperBase(const TBWIN32WindowHelperBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TBWIN32WindowHelperBase::~TBWIN32WindowHelperBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void TBWIN32WindowHelperBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TBWIN32WindowHelper *pThis = static_cast<TBWIN32WindowHelper *>(this);

    pThis->execSync(static_cast<TBWIN32WindowHelper *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TBWIN32WindowHelperBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TBWIN32WindowHelper *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TBWIN32WindowHelper *>(pRefAspect),
                  dynamic_cast<const TBWIN32WindowHelper *>(this));

    return returnValue;
}
#endif

void TBWIN32WindowHelperBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
