/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBWIN32WINDOWFIELDS_H_
#define _OSGTBWIN32WINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGWindowWIN32Def.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TBWIN32Window;

OSG_GEN_CONTAINERPTR(TBWIN32Window);
/*! \ingroup GrpWindowWIN32FieldTraits
    \ingroup GrpLibOSGWindowWIN32
 */
template <>
struct FieldTraits<TBWIN32Window *, nsOSG> :
    public FieldTraitsFCPtrBase<TBWIN32Window *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TBWIN32Window *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_WINDOWWIN32_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTBWIN32WindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBWIN32Window *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTBWIN32WindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32Window *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTBWIN32WindowPtr;
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32Window *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTBWIN32WindowPtr;
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32Window *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTBWIN32WindowPtr;
/*! \ingroup GrpWindowWIN32FieldSFields */
typedef PointerSField<TBWIN32Window *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTBWIN32WindowPtr;


/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32Window *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTBWIN32WindowPtr;
/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32Window *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTBWIN32WindowPtr;
/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32Window *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTBWIN32WindowPtr;
/*! \ingroup GrpWindowWIN32FieldMFields */
typedef PointerMField<TBWIN32Window *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTBWIN32WindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindowWIN32 */
struct SFRecTBWIN32WindowPtr : 
    public PointerSField<TBWIN32Window *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindowWIN32 */
struct SFUnrecTBWIN32WindowPtr : 
    public PointerSField<TBWIN32Window *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindowWIN32 */
struct SFWeakTBWIN32WindowPtr :
    public PointerSField<TBWIN32Window *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldSFields \ingroup GrpLibOSGWindowWIN32 */
struct SFUncountedTBWIN32WindowPtr :
    public PointerSField<TBWIN32Window *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindowWIN32 */
struct MFRecTBWIN32WindowPtr :
    public PointerMField<TBWIN32Window *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindowWIN32 */
struct MFUnrecTBWIN32WindowPtr :
    public PointerMField<TBWIN32Window *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindowWIN32 */
struct MFWeakTBWIN32WindowPtr :
    public PointerMField<TBWIN32Window *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpWindowWIN32FieldMFields \ingroup GrpLibOSGWindowWIN32 */
struct MFUncountedTBWIN32WindowPtr :
    public PointerMField<TBWIN32Window *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTBWIN32WINDOWFIELDS_H_ */
