/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TBWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGWindowEventProducer.h"     // WindowEventProducer Class

#include "OSGTBWindowBase.h"
#include "OSGTBWindow.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TBWindow
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var WindowEventProducer * TBWindowBase::_sfWindowEventProducer
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TBWindow *, nsOSG>::_type(
    "TBWindowPtr", 
    "WindowPtr", 
    TBWindow::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TBWindow *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TBWindow *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TBWindow *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TBWindowBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecWindowEventProducerPtr::Description(
        SFUnrecWindowEventProducerPtr::getClassType(),
        "WindowEventProducer",
        "",
        WindowEventProducerFieldId, WindowEventProducerFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TBWindow::editHandleWindowEventProducer),
        static_cast<FieldGetMethodSig >(&TBWindow::getHandleWindowEventProducer));

    oType.addInitialDesc(pDesc);
}


TBWindowBase::TypeObject TBWindowBase::_type(
    TBWindowBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    TBWindow::initMethod,
    TBWindow::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TBWindow::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TBWindow\"\n"
    "    parent=\"Window\"\n"
    "    library=\"System\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    ">\n"
    "    <Field\n"
    "        name=\"WindowEventProducer\"\n"
    "        type=\"WindowEventProducerPtr\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "\t\tdefaultValue=\"nullptr\"\n"
    "\t\tfieldHeader=\"OSGWindowEventProducerFields.h\"\n"
    "    >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TBWindowBase::getType(void)
{
    return _type;
}

const FieldContainerType &TBWindowBase::getType(void) const
{
    return _type;
}

UInt32 TBWindowBase::getContainerSize(void) const
{
    return sizeof(TBWindow);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TBWindow::_sfWindowEventProducer field.
const SFUnrecWindowEventProducerPtr *TBWindowBase::getSFWindowEventProducer(void) const
{
    return &_sfWindowEventProducer;
}

SFUnrecWindowEventProducerPtr *TBWindowBase::editSFWindowEventProducer(void)
{
    editSField(WindowEventProducerFieldMask);

    return &_sfWindowEventProducer;
}





/*------------------------------ access -----------------------------------*/

SizeT TBWindowBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (WindowEventProducerFieldMask & whichField))
    {
        returnValue += _sfWindowEventProducer.getBinSize();
    }

    return returnValue;
}

void TBWindowBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (WindowEventProducerFieldMask & whichField))
    {
        _sfWindowEventProducer.copyToBin(pMem);
    }
}

void TBWindowBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (WindowEventProducerFieldMask & whichField))
    {
        editSField(WindowEventProducerFieldMask);
        _sfWindowEventProducer.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

TBWindowBase::TBWindowBase(void) :
    Inherited(),
    _sfWindowEventProducer    (nullptr)
{
}

TBWindowBase::TBWindowBase(const TBWindowBase &source) :
    Inherited(source),
    _sfWindowEventProducer    (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TBWindowBase::~TBWindowBase(void)
{
}

void TBWindowBase::onCreate(const TBWindow *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        TBWindow *pThis = static_cast<TBWindow *>(this);

        pThis->setWindowEventProducer(source->getWindowEventProducer());
    }
}

GetFieldHandlePtr TBWindowBase::getHandleWindowEventProducer (void) const
{
    SFUnrecWindowEventProducerPtr::GetHandlePtr returnValue(
        new  SFUnrecWindowEventProducerPtr::GetHandle(
             &_sfWindowEventProducer,
             this->getType().getFieldDesc(WindowEventProducerFieldId),
             const_cast<TBWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TBWindowBase::editHandleWindowEventProducer(void)
{
    SFUnrecWindowEventProducerPtr::EditHandlePtr returnValue(
        new  SFUnrecWindowEventProducerPtr::EditHandle(
             &_sfWindowEventProducer,
             this->getType().getFieldDesc(WindowEventProducerFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TBWindow::setWindowEventProducer,
                    static_cast<TBWindow *>(this), _1));

    editSField(WindowEventProducerFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TBWindowBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TBWindow *pThis = static_cast<TBWindow *>(this);

    pThis->execSync(static_cast<TBWindow *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TBWindowBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TBWindow *>(this)->setWindowEventProducer(NULL);


}


OSG_END_NAMESPACE
